---
- name: Download Microsoft GPG key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc
    mode: '0644'
  become: yes

- name: Dearmor Microsoft GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/microsoft.gpg /tmp/microsoft.asc
  args:
    creates: /usr/share/keyrings/microsoft.gpg
  become: yes

- name: Add Visual Studio Code repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: present
  become: yes
  notify: Update apt cache

- name: Install Visual Studio Code
  ansible.builtin.apt:
    name: code
    state: present
  become: yes