---
- name: Download Microsoft GPG key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc
    mode: '0644'
  become: yes

- name: Dearmor Microsoft GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg /tmp/microsoft.asc
    creates: /etc/apt/keyrings/microsoft.gpg
  become: yes

- name: Add Visual Studio Code repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: present
  become: yes

- name: Update apt cache to recognize new VS Code repository
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install Visual Studio Code
  ansible.builtin.apt:
    name: code
    state: present
  become: yes