---
- name: Download HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp.gpg
    mode: '0644'
  become: yes

- name: Check if HashiCorp GPG key already exists
  ansible.builtin.stat:
    path: /etc/apt/keyrings/hashicorp.gpg
  register: hashicorp_gpg_key

- name: Dearmor HashiCorp GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/hashicorp.gpg /tmp/hashicorp.gpg
  become: yes
  when: not hashicorp_gpg_key.stat.exists
  changed_when: true

- name: Add HashiCorp repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp
    state: present
  become: yes
  notify: Update apt cache

- name: Install Vagrant
  ansible.builtin.apt:
    name: vagrant
    state: present
  become: yes