---
- name: Update apt package cache with --allow-releaseinfo-change
  ansible.builtin.apt:
    update_cache: yes
    # This passes the desired flag directly to the apt-get command.
    update_cache_args: "--allow-releaseinfo-change"
  become: yes

- name: Upgrade all apt packages to the latest version
  ansible.builtin.apt:
    upgrade: dist
  become: yes
