---

- name: Update apt package cache with --allow-releaseinfo-change (shell)
  ansible.builtin.shell:
    cmd: apt-get update --allow-releaseinfo-change
  become: yes  

- name: Upgrade all apt packages to the latest version
  ansible.builtin.apt:
    upgrade: dist
  become: yes
