---
# - name: Find potentially conflicting repository files
#   ansible.builtin.find:
#     paths: /etc/apt/sources.list.d/
#     patterns:
#       - "vscode*"
#       - "microsoft*"
#       - "hashicorp*"
#       - "virtualbox*"
#       - "docker*"
#     file_type: file
#   register: old_repo_files
#   become: yes

# - name: Remove conflicting repository files
#   ansible.builtin.file:
#     path: "{{ item.path }}"
#     state: absent
#   become: yes
#   loop: "{{ old_repo_files.files }}"
#   loop_control:
#     label: "{{ item.path }}"

# - name: Find potentially conflicting GPG key files
#   ansible.builtin.find:
#     paths: /etc/apt/keyrings/
#     patterns:
#       - "*docker*"
#       - "*hashicorp*"
#       - "*microsoft*"
#       - "*vscode*"
#       - "*virtualbox*"
#     file_type: file
#   register: old_gpg_files
#   become: yes

# - name: Remove conflicting GPG key files
#   ansible.builtin.file:
#     path: "{{ item.path }}"
#     state: absent
#   become: yes
#   loop: "{{ old_gpg_files.files }}"
#   loop_control:
#     label: "{{ item.path }}"

- name: Install common prerequisites for external repositories
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - gnupg
      - htop
      - python3-pip
      - python3-venv
      - wget
      - git
    state: present
  become: yes


- name: Create directory for GPG keys if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes