---
- name: Apply auditd ruleset from local copy
  ansible.builtin.copy:
    src: auditd_rules/audit.rules
    dest: /etc/audit/audit.rules
    owner: root
    group: root
    mode: '0640'
    backup: yes
  become: yes
  notify: restart auditd
