---
- name: Verify
  hosts: all
  become: yes
  tasks:
    - name: Run the converge playbook a second time to test for idempotence
      ansible.builtin.include_playbook:
        file: "{{ molecule_ephemeral_directory }}/converge.yml"
      register: second_converge_result

    - name: Fail if the second converge run made any changes
      ansible.builtin.assert:
        that:
          - second_converge_result.changed | int == 0
        fail_msg: "Idempotence check failed. The role made changes on the second run."
